// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuOZ7mHZ93nnN7PvYrUDVKcnEjYW82S_w',
    appId: '1:593291053883:web:2259eff818377a8b09051e',
    messagingSenderId: '593291053883',
    projectId: 'mira-1fdc3',
    authDomain: 'mira-1fdc3.firebaseapp.com',
    storageBucket: 'mira-1fdc3.firebasestorage.app',
    measurementId: 'G-DNP3CE3E7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3bxYHT2ZYRNeMckMkHWzgC6fX4L_PK6M',
    appId: '1:593291053883:android:ddf6b3873819b4b709051e',
    messagingSenderId: '593291053883',
    projectId: 'mira-1fdc3',
    storageBucket: 'mira-1fdc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHIx44p9xsXJTtb926e_-k6NYdQSgq-20',
    appId: '1:593291053883:ios:c2670e4419fa681409051e',
    messagingSenderId: '593291053883',
    projectId: 'mira-1fdc3',
    storageBucket: 'mira-1fdc3.firebasestorage.app',
    androidClientId: '593291053883-e5askargi4p2cb1vghe9fh3llgiqfj7b.apps.googleusercontent.com',
    iosClientId: '593291053883-jngmu7luvem85sjm7523501jeeurto11.apps.googleusercontent.com',
    iosBundleId: 'com.koralabs.mira',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHIx44p9xsXJTtb926e_-k6NYdQSgq-20',
    appId: '1:593291053883:ios:c2670e4419fa681409051e',
    messagingSenderId: '593291053883',
    projectId: 'mira-1fdc3',
    storageBucket: 'mira-1fdc3.firebasestorage.app',
    androidClientId: '593291053883-e5askargi4p2cb1vghe9fh3llgiqfj7b.apps.googleusercontent.com',
    iosClientId: '593291053883-jngmu7luvem85sjm7523501jeeurto11.apps.googleusercontent.com',
    iosBundleId: 'com.koralabs.mira',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuOZ7mHZ93nnN7PvYrUDVKcnEjYW82S_w',
    appId: '1:593291053883:web:b1d4cedcf65ba81809051e',
    messagingSenderId: '593291053883',
    projectId: 'mira-1fdc3',
    authDomain: 'mira-1fdc3.firebaseapp.com',
    storageBucket: 'mira-1fdc3.firebasestorage.app',
    measurementId: 'G-SPMK8T1815',
  );

}