// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuOZ7mHZ93nnN7PvYrUDVKcnEjYW82S_w',
    appId: '1:593291053883:web:8e5ad69cd21cc70209051e',
    messagingSenderId: '593291053883',
    projectId: 'mira-1fdc3',
    authDomain: 'mira-1fdc3.firebaseapp.com',
    storageBucket: 'mira-1fdc3.firebasestorage.app',
    measurementId: 'G-N50G7QBTRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3bxYHT2ZYRNeMckMkHWzgC6fX4L_PK6M',
    appId: '1:593291053883:android:3115a83d8d4e852309051e',
    messagingSenderId: '593291053883',
    projectId: 'mira-1fdc3',
    storageBucket: 'mira-1fdc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHIx44p9xsXJTtb926e_-k6NYdQSgq-20',
    appId: '1:593291053883:ios:f42d103a0403414209051e',
    messagingSenderId: '593291053883',
    projectId: 'mira-1fdc3',
    storageBucket: 'mira-1fdc3.firebasestorage.app',
    iosClientId:
        '593291053883-4hu1pd574kfbncgqs75qgh8p6jukaprk.apps.googleusercontent.com',
    iosBundleId: 'com.koralabs.mira',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHIx44p9xsXJTtb926e_-k6NYdQSgq-20',
    appId: '1:593291053883:ios:f42d103a0403414209051e',
    messagingSenderId: '593291053883',
    projectId: 'mira-1fdc3',
    storageBucket: 'mira-1fdc3.firebasestorage.app',
    iosClientId:
        '593291053883-4hu1pd574kfbncgqs75qgh8p6jukaprk.apps.googleusercontent.com',
    iosBundleId: 'com.koralabs.mira',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuOZ7mHZ93nnN7PvYrUDVKcnEjYW82S_w',
    appId: '1:593291053883:web:6877e06021181aa609051e',
    messagingSenderId: '593291053883',
    projectId: 'mira-1fdc3',
    authDomain: 'mira-1fdc3.firebaseapp.com',
    storageBucket: 'mira-1fdc3.firebasestorage.app',
    measurementId: 'G-GTMX79Z4EE',
  );
}
